image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --update py-pip &&
      pip install docker-compose
  - docker login -u nvTran -p HzBxTohgcRYXBcs7tPno registry.gitlab.com



test:
  stage: test
  script: echo "No testing setup yet"
    
build:
  stage: build
  tags:
    - docker
  script:
    - echo "start building app"
    - docker build -t registry.gitlab.com/dangvu1986/dvblog .
    - docker push registry.gitlab.com/dangvu1986/dvblog
    

  only:
    - master

staging:
  stage: deploy
  script:
    - docker run -p 8000:8000 -i -t dvblog