image: docker:18.09.7
services:
  - docker:18.09.7-dind


stages:
  - build
  - test
  - deploy

before_script:
  # - apk add --update py-pip &&
  #     pip install docker-compose
  - docker login -u nvTran -p HzBxTohgcRYXBcs7tPno registry.gitlab.com




test:
  stage: test
  script: echo "No testing setup yet"
    
build:
  stage: build
  tags:
    - docker
  script:
    - echo "start building app"
    - docker build -t registry.gitlab.com/dangvu1986/dvblog .
    - docker push registry.gitlab.com/dangvu1986/dvblog
    

  only:
    - master

staging:
  stage: deploy
  script:
    - docker pull registry.gitlab.com/dangvu1986/dvblog:latest
    - docker run -p 8000:8000 -i  gitlab.com/dangvu1986/dvblog:latest
variables:
  DOCKER_HOST: tcp://docker:2375
