stages:
  - build
  - test
  - deploy

before_script:
  # - apk add --update py-pip &&
  #     pip install docker-compose
  # - docker login -u nvTran -p HzBxTohgcRYXBcs7tPno registry.gitlab.com
  # - cd /home/truongannt97/dvblog



test:
  stage: test
  script: 
    - echo "No testing setup yet"
    
# build:
#   stage: build
#   tags:
#     - docker
#   script:
#     - echo "start building app"

#   only:
#     - master

staging:
  stage: deploy
  script:
    # - docker pull registry.gitlab.com/dangvu1986/dvblog:latest
    # - docker build -t registry.gitlab.com/dangvu1986/dvblog .
    # - docker run -p 8000:8000 -i  registry.gitlab.com/dangvu1986/dvblog:latest
# variables:
#   DOCKER_HOST: tcp://docker:2375
      # - sudo pip3 uninstall Django
      - sudo systemctl stop gunicorn
      - 
      - git pull git@gitlab.com:dangvu1986/dvblog.git

      - sudo systemctl start gunicorn
      - sudo systemctl enable gunicorn
      

